#!/bin/sh

# $Header: /data1/home/kim/devel/cvsprojects/nextrieve-2.0.28/Build,v 1.1.1.1 2007/07/01 19:58:57 kim Exp $

# Make installation from start to finish

SYSTEM=`uname -s`

if [ "$SYSTEM" != "HP-UX" ] ; then
    # If this is an HP, then we have to run xmkmf separately and edit
    # the Makefile and remove the -Aa flag first
    xmkmf
fi

make depend
cd expat*
./configure
if [ "$SYSTEM" = "HP-UX" -o "$SYSTEM" = "BSD/OS" ] ; then
    cd lib
    make
    cd ../../
else
    make
    cd ..
fi

cd zlib*
./configure
make
cd ..
make
make installation

exit 0
