/* config.h.  Generated by configure.  */

/* Define as 1 if <semaphore.h> exists. */
#define HAVE_SEMAPHORE_H 1

/* Define as 1 if <sys/types.h> exists. */
#define HAVE_SYS_TYPES_H 1

/* Define as 1 if we have wcscoll. */
#define HAVE_WCSCOLL 1

/* Define as 1 if we can use threads. */
/* #undef CAN_USE_THREADS */

/* Define as 1 if we've got sin_len in sockaddr_in. */
/* #undef HAVE_STRUCT_SOCKADDR_IN_SIN_LEN */

/* #undef HAVE_STRUCT_SOCKADDR_IN_SIN_PORT */

#if defined(CAN_USE_THREADS) && defined(USE_THREADS)
#define USING_THREADS 1
#define _REENTRANT 1
#define THREAD_SAFE 1
#define _THREAD_SAFE 1
#endif

#if !defined(__FreeBSD__) && defined(HAVE_SEMAPHORE_H)
#define USING_SEMAPHORE_H
#endif
